---
- name: Install nginx and certbot
  apt:
    name:
      - nginx
      - certbot
      - python3-certbot-dns-route53
    state: present

- name: Obtain letsencrypt certificate
  command: "certbot certonly --dns-route53 -d *.{{ domain }} -m {{ letsencrypt_email }} --no-eff-email --agree-tos -n"

- name: Copy base nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644

- name: Copy nginx letsencrypt.conf
  copy:
    src: letsencrypt.conf
    dest: /etc/nginx/letsencrypt.conf
    mode: 0644

- name: Template nginx site configs
  template:
    src: site.conf.j2
    dest: "/etc/nginx/conf.d/{{ site.sub_domain }}.conf"
    mode: 0644
  loop: "{{ sites }}"
  loop_control:
    loop_var: site

- name: Copy ca verification cert
  when: ca_certificate is defined
  block:
    - name: Make nginx ssl directory
      file:
        path: /etc/nginx/ssl/
        state: directory
        mode: 0755
    
    - name: Copy ssl_verify_client ca cert
      copy:
        src: "{{ ca_certificate }}"
        dest: /etc/nginx/ssl/ca.crt
        mode: 0644

- name: Restart and enable nginx service
  systemd:
    daemon_reload: yes
    name: nginx.service
    state: restarted
    enabled: yes
