---
- name: Install nginx and certbot
  apt:
    name:
      - nginx
      - certbot
      - python3-certbot-dns-route53
    state: present

- name: Obtain letsencrypt certificate
  command: "certbot certonly --dns-route53 -d *.{{ domain }} -m {{ letsencrypt_email }} --no-eff-email --agree-tos -n"

- name: Copy base nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644

- name: Copy nginx letsencrypt.conf
  copy:
    src: letsencrypt.conf
    dest: /etc/nginx/letsencrypt.conf
    mode: 0644

- name: Template sites nginx config
  template:
    src: site.conf.j2
    dest: "/etc/nginx/conf.d/{{ site.sub_domain }}.conf"
    mode: 0644
  loop: "{{ sites }}"
  loop_control:
    loop_var: site

- name: Remove sites from hosts file
  lineinfile:
    path: /etc/hosts
    regexp: ".*# rproxy managed$"
    state: absent

- name: Add sites to hosts file
  include_tasks: add-site.yml
  loop: "{{ sites }}"
  loop_control:
    loop_var: site

- name: Make nginx ssl directory
  file:
    path: /etc/nginx/ssl/
    state: directory
    mode: 0755

- name: Copy ssl_verify_client ca cert
  copy:
    src: ca.crt
    dest: /etc/nginx/ssl/ca.crt
    mode: 0644

- name: Copy custom nginx service file
  copy:
    src: nginx.service
    dest: /etc/systemd/system/nginx.service
    mode: 0644

- name: Start and enable systemd-resolved service
  systemd:
    name: systemd-resolved.service
    state: started
    enabled: yes

- name: Restart and enable nginx service
  systemd:
    daemon_reload: yes
    name: nginx.service
    state: restarted
    enabled: yes
