---
- name: Check if aws cli is installed
  stat:
    path: /usr/local/bin/aws
  register: aws_cli

- name: Install aws cli
  when: not aws_cli.stat.exists
  block:
    - name: Download and unzip aws cli
      unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/
        remote_src: yes

    - name: Run aws cli install script
      command: /tmp/aws/install

- name: Create aws cli config dir
  file:
    path: /root/.aws
    state: directory
    mode: 0755

- name: Template aws cli credentials config
  template:
    src: credentials.j2
    dest: /root/.aws/credentials
    mode: 0600
