---
- name: Check if aws cli is installed
  block:
    - name: Check for aws binary
      command: which aws

  rescue:
    - name: Download and unzip arm aws cli
      unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip
        dest: /tmp/
        remote_src: yes

    - name: Install aws cli
      command: /tmp/aws/install

- name: Create aws cli config dir
  file:
    path: /root/.aws
    state: directory
    mode: 0755

- name: Template aws cli credentials config
  template:
    src: credentials.j2
    dest: /root/.aws/credentials
    mode: 0600
    force: yes
