---
rpi:
  hosts:
    192.168.1.0:

  vars:
    # \\052 = *
    aws_record_name: '\\052.example.com'
    aws_hosted_zone_id: 1234HOSTEDZONEID12345

    letsencrypt_email: email@example.com

    domain: example.com
    sites:
      - { sub_domain: nextcloud,
          proxy_pass: https://nextcloud.example.com,
          ssl_verify_client: no,
          hosts_entry: 192.168.1.2
        }

      - { sub_domain: plex,
          proxy_pass: https://plex.example.com,
          ssl_verify_client: yes,
          hosts_entry: 192.168.1.3
        }

    wireguard_server_sub_domain: vpn
    wireguard_server_address: 192.168.2.1
    wireguard_server_port: 51820

    wireguard_clients:
      - { name: client1,
          address: 192.168.2.2,
          allowed_ips: 0.0.0.0/0
      }

      - { name: client2,
          address: 192.168.2.3,
          allowed_ips: 0.0.0.0/0
      }
