---
all:
  hosts:
    rproxy:
      ansible_host: 192.168.1.0
      ansible_ssh_user: root

      aws_record_name: '\\052.example.com'      # AWS record used for dynamic DNS (\\052 is * also known as wilcard record)
      aws_hosted_zone_id: HOSTEDZONEID123456789 # AWS hosted zone ID

      # address for receiving Let's Encrypt certificate expiration alerts
      letsencrypt_email: email@example.com

      domain: example.com                   # domain
      ca_certificate: ca.crt                # certificate used for verifying site clients
      sites:
        - sub_domain: nextcloud             # subdomain
          proxy_host: nextcloud.example.com # FQDN/hostname/IP to proxy requests to
          proxy_https: yes                  # use https for proxying requests (optional)

        - sub_domain: plex
          proxy_host: plex.internal
          ssl_verify_client: yes            # require client certificate to connect to host (optional)

      wireguard_server_sub_domain: vpn               # combined with domain to generate public server address used by clients to connect
      wireguard_server_port: 51820                   # public server port used by clients to connect
      wireguard_internal_network: 192.168.1.0/24     # internal network wireguard gives access to
      wireguard_internal_dns: 192.168.1.1            # internal network DNS server
      wireguard_server_address: 192.168.2.1          # server address of wireguard on wireguard network

      wireguard_clients:
        - name: user1           # client name
          address: 192.168.2.2  # client address on wireguard network 
          allowed_ips: "{{ wireguard_server_address }}/32, {{ wireguard_internal_network }}"
          private_key: !vault | # client private key (generated using: make encrypt_string)
            $ANSIBLE_VAULT;1.1;AES256
            0000000000000000000000000000000000000000000000000000000000000000000000000000000
            0000000000000000000000000000000000000000000000000000000000000000000000000000000
            0000000000000000000000000000000000000000000000000000000000000000000000000000000
            0000000000000000000000000000000000000000000000000000000000000000000000000000000
            0000

        - name: user2
          address: 192.168.2.3
          # specifies what IPs the client is allowed to connect to (don't modify unless you know what you're doing)
          allowed_ips: "{{ wireguard_server_address }}/32, {{ wireguard_internal_network }}"
          private_key: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            0000000000000000000000000000000000000000000000000000000000000000000000000000000
            0000000000000000000000000000000000000000000000000000000000000000000000000000000
            0000000000000000000000000000000000000000000000000000000000000000000000000000000
            0000000000000000000000000000000000000000000000000000000000000000000000000000000
            0000
