---
- name: Copy apt update script
  copy:
    src: apt-update.sh
    dest: /usr/local/bin/apt-update.sh
    mode: 0755

- name: Copy apt update service and timer
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/
  loop:
    - "apt-update.service"
    - "apt-update.timer"

- name: Systemd daemon-reload
  systemd:
    daemon_reload: yes
  become: yes

- name: Enable apt-update.timer
  systemd:
    name: apt-update.timer
    state: started
    enabled: yes
