---
- name: Template firewall configuration
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: 0755
    force: yes

- name: Restart and enable nftables
  systemd:
    name: nftables
    state: restarted
    enabled: yes
