---
- name: Install python3 and pip
  apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Install aws-ddns dependencies
  pip:
    requirements: https://raw.githubusercontent.com/basharkey/aws-ddns/main/requirements.txt

- name: Install aws-ddns
  get_url:
    url: https://raw.githubusercontent.com/basharkey/aws-ddns/main/aws-ddns.py
    dest: /usr/local/bin/aws-ddns
    mode: 0755

- name: Template aws-ddns service and timer
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    mode: 0755
  loop:
    - aws-ddns.service
    - aws-ddns.timer

- name: Restart and enable aws-ddns timer
  systemd:
    daemon_reload: yes
    name: aws-ddns.timer
    state: restarted
    enabled: yes
