---
- name: "Create {{ client.name }} wireguard  private key"
  when: client.private_key is not defined
  block:
    - name: "Generate {{ client.name }} wireguard private key"
      command: wg genkey
      register: private_key

    - name: "Set {{ client.name }} wireguard private key var"
      set_fact:
        wireguard_clients: "{{ wireguard_clients
          | rejectattr('name', 'equalto', client.name)
          | list + [ client | combine({ 'private_key': private_key }) ] }}"

- debug:
    var: private_key
