---
- name: "Create {{ client }} wireguard  private key"
  when: wireguard_sever_private_key is not defined
  block:
    - name: "Generate {{ client }} wireguard private key"
      command: wg genkey
      register: private_key
    - set_fact:
        private_key: private_key.result

    - name: "Set {{ client }} wireguard private key var"
      set_fact:
        wireguard_clients: "{{ wireguard_clients
          | rejectattr('name', 'equalto', client.name)
          | list + [ item | combine({ 'private_key': private_key }) ] }}"

- name: "Generate {{ client }} wireguard public key"
  shell: "echo {{ client.private_key }} | wg pubkey"
  register: public_key
- set_fact:
    public_key: public_key.result

- name: "Set {{ client }} wireguard public key var"
  set_fact:
    wireguard_clients: "{{ wireguard_clients
      | rejectattr('name', 'equalto', client.name)
      | list + [ item | combine({ 'public_key': public_key }) ] }}"
