---
- name: Install wireguard
  apt:
    name: wireguard
    state: latest

- name: Stat wireguard server private key file
  stat:
    path: /etc/wireguard/privatekey
  register: privatekey

- name: Stat wireguard server public key file
  stat:
    path: /etc/wireguard/publickey
  register: publickey

- name: Check if wireguard server private key file exists
- when: not privatekey.stat.exists
  block:
    - name: Generate wireguard server private key
      command: wg genkey
      register: result

    - name: Create wireguard server private key file
      copy:
        content: "{{ result.stdout }}"
        dest: /etc/wireguard/privatekey

- name: Check if wireguard server public key file exists
  when: not publickey.stat.exists
  block:
    - name: Generate wireguard server public key
      shell: cat /etc/wireguard/privatekey | wg pubkey
      register: result

    - name: Create wireguard server public key file
      copy:
        content: "{{ result.stdout }}"
        dest: /etc/wireguard/publickey


- name: Load wireguard server private key from file
  slurp:
    src: /etc/wireguard/privatekey
  register: result

- name: Set wireguard server private key var
  set_fact:
    wireguard_server_private_key: "{{ result.content | b64decode | trim }}"

- name: Load wireguard server public key from file
  slurp:
    src: /etc/wireguard/publickey
  register: result

- name: Set wireguard server public key var
  set_fact:
    wireguard_server_public_key: "{{ result.content | b64decode | trim }}"


- name: Create wireguard client config directory
  file:
    path: /etc/wireguard/clients/
    state: directory
    mode: 0700

- name: Generate wireguard client keys
  loop: "{{ wireguard_clients }}"
  include_tasks: generate-client-keys.yml

- name: Template wireguard client configs
  loop: "{{ wireguard_clients }}"
  template:
    src: wg0-client.conf.j2
    dest: "/etc/wireguard/clients/{{ item.name }}-wg0.conf"
    mode: 0644
    force: yes

- name: Template wireguard server config
  template:
    src: wg0-server.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: 0644
    force: yes

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: Systemd daemon-reload
  systemd:
    daemon_reload: yes

- name: Start and enable wireguard server systemd sevice
  systemd:
    name: wg-quick@wg0.service
    state: restarted
    enabled: yes
