---
- name: Install wireguard
  apt:
    name: wireguard
    state: present

- name: Create wireguard server private key
  when: wireguard_sever_private_key is not defined
  block:
    - name: Generate wireguard server private key
      command: wg genkey
      register: wireguard_server_private_key
    - set_fact:
        wireguard_server_private_key: wireguard_server_private_key.result

- name: Generate wireguard server public key
  shell: "echo {{ wireguard_server_private_key }} | wg pubkey"
  register: wireguard_server_public_key
- set_fact:
    wireguard_server_public_key: wireguard_server_public_key.result

- name: Create wireguard client config directory
  file:
    path: "/etc/wireguard/clients"
    state: directory
    mode: 0700

- name: Generate wireguard client keys 
  include_tasks: generate-client-keys.yml
  loop: "{{ wireguard_clients }}"
  loop_control:
    loop_var: client

- name: Template wireguard client configs
  template:
    src: client-wg0.conf.j2
    dest: "/etc/wireguard/clients/{{ client.name }}-wg0.conf"
    mode: 0644
  loop: "{{ wireguard_clients }}"
  loop_control:
    loop_var: client

- name: Template wireguard server config
  template:
    src: server-wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: 0644

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: Start and enable wireguard server systemd sevice
  systemd:
    daemon_reload: yes
    name: wg-quick@wg0.service
    state: restarted
    enabled: yes
